name: "Build Storybook"
description: "Builds storybook"
inputs:
    NODE_ENV:
        description: "Target env we are going to build assets"
        required: true
        default: "production"
runs:
    using: "composite"
    steps:
        - run: |
              [ -d .ghpages-artifact ] || mkdir .ghpages-artifact
          shell: bash
        - run: NODE_ENV=${{ inputs.NODE_ENV }} npm run build:storybook
          shell: bash

        - name: Grant permissions for a folder containing artifact (needed for upload-pages-artifact action)
          run: |
              chmod -c -R +rX ".ghpages-artifact/" | while read line; do
                  echo "::warning title=Invalid file permissions automatically fixed::$line"
              done
          shell: bash

        - name: Archive GitHub Pages Artifact
          uses: actions/upload-pages-artifact@v3
          with:
              name: "github-pages"
              path: ".ghpages-artifact/storybook"
